version: '3.4'

services:
  image_storage:
    container_name: image_storage
    restart: always
    ports:
      - "8080:80"
    volumes:
      - image_storage_data:/var/www/html
    environment:
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin

  images.api:
    container_name: images.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "NextCloudSettings:Url=http://image_storage:80"
      - "NextCloudSettings:UserName=admin"
      - "NextCloudSettings:Password=admin"
    depends_on:
      - image_storage
    ports:
      - "8001:80"
