version: '3.4'

services:
  images.api:
    container_name: images.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "MyNextCloudSettings:Url=http://image_storage"
      - "MyNextCloudSettings:UserName=admin"
      - "MyNextCloudSettings:Password=admin"
    ports:
      - "8001:80"
    volumes:
      - image_storage_data:/app/images