version: '3.4'

services:
  images.api:
    image: ${DOCKER_REGISTRY-}imagesapi
    build:
      context: .
      dockerfile: src/Services/Images/Api/Images.Api/Dockerfile

volumes:
  image_storage_data:
