version: '3.4'

services:
  images.api:
    container_name: images.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8001:80"
    volumes:
      - image_storage_data:/app/images